# Generated by Django 3.2.9 on 2021-12-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('can_see_companies', 'Can see companies'),)},
        ),
    ]
