# Generated by Django 3.2.10 on 2021-12-15 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCRM', '0003_messagedislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'verbose_name': 'communication'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-date_created'], 'permissions': (('can_see_companies', 'Can see companies'),), 'verbose_name': 'company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companydislike',
            options={'ordering': ['-created'], 'verbose_name': 'dislike of company', 'verbose_name_plural': 'Dislikes of companies'},
        ),
        migrations.AlterModelOptions(
            name='companylikes',
            options={'ordering': ['-created'], 'verbose_name': 'like of company', 'verbose_name_plural': 'Likes of companies'},
        ),
        migrations.AlterModelOptions(
            name='emailcompany',
            options={'ordering': ['-created'], 'verbose_name': 'email of company', 'verbose_name_plural': 'Emails of companies'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created'], 'verbose_name': 'comment of project', 'verbose_name_plural': 'Comments of projects'},
        ),
        migrations.AlterModelOptions(
            name='messagedislike',
            options={'ordering': ['-created'], 'verbose_name': 'dislike of message', 'verbose_name_plural': 'Dislikes of messages'},
        ),
        migrations.AlterModelOptions(
            name='messagelike',
            options={'ordering': ['-created'], 'verbose_name': 'like of message', 'verbose_name_plural': 'Likes of messages'},
        ),
        migrations.AlterModelOptions(
            name='phonecompany',
            options={'ordering': ['-created'], 'verbose_name': 'phone of company', 'verbose_name_plural': 'Phones of companies'},
        ),
        migrations.AlterModelOptions(
            name='projectcompany',
            options={'ordering': ['-created'], 'verbose_name': 'project of company', 'verbose_name_plural': 'Project of companies'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='emailcompany',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonecompany',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcompany',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
