# Generated by Django 3.2.9 on 2021-12-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCRM', '0003_auto_20211207_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='company',
        ),
        migrations.AddField(
            model_name='message',
            name='communication_options',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='MiniCRM.communication'),
            preserve_default=False,
        ),
    ]
