# Generated by Django 3.2.10 on 2021-12-16 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCRM', '0004_auto_20211215_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcompany',
            options={'ordering': ['-created'], 'verbose_name': 'project of company', 'verbose_name_plural': 'Projects of companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
