# Generated by Django 3.2.10 on 2021-12-23 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCRM', '0005_auto_20211216_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MiniCRM.company'),
        ),
    ]
