# Generated by Django 3.2.9 on 2021-12-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCRM', '0005_remove_message_communication_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Communication',
        ),
    ]
