# Generated by Django 3.2.9 on 2021-12-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCRM', '0007_auto_20211208_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='communication_options',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MiniCRM.communication'),
            preserve_default=False,
        ),
    ]
