# Generated by Django 3.2.9 on 2021-12-08 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCRM', '0009_auto_20211208_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='communication',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='emailcompany',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='phonecompany',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number must be in format: "+380999999999"', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: "+380999999999". Up to "+380" and 9 digits.', regex='^\\+380\\d{9}')]),
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
