# Generated by Django 3.2.10 on 2021-12-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCRM', '0011_messagelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylikes',
            name='like',
            field=models.BooleanField(default=None, null=True, verbose_name='Like'),
        ),
    ]
