# Generated by Django 3.2.10 on 2021-12-12 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MiniCRM', '0012_alter_companylikes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylikes',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Like'),
        ),
        migrations.CreateModel(
            name='CompanyDisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.BooleanField(default=False, verbose_name='DisLike')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MiniCRM.company')),
                ('disliked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
